name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v16
      with:
        name: purcellimages
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build --accept-flake-config ./.
